name: "csn-pipeline-test"

on:
  push:
    branches:
      - main

jobs:
  test:
    name: "csn-test"
    runs-on: self-hosted
   # env:
   #   AWS_ACCESS_KEY_ID: ${{ secrets.AWS_ACCESS_KEY_ID }}
   #   AWS_SECRET_ACCESS_KEY: ${{ secrets.AWS_SECRET_ACCESS_KEY }}

   # defaults:
   #   run:
   #     working-directory: source
    steps:
      - name: Checkout Repo
        uses: actions/checkout@v2

      - name: check working directory
        run: pwd

      - name: install docker
        run: sudo apt install docker.io

      - name: check the containers that are running
        run: docker --version